name: 3.7.12-ohos-1.0.6

on:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - '*'
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 登录 GitHub Package Registry
      - name: Log in to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          sed -i 's/--VERSION--/3.7.12-ohos-1.0.6/g' Dockerfile
          docker build -t ghcr.io/${{ github.repository }}/image:3.7.12-ohos-1.0.6 .

      # 4. 推送 Docker 镜像到 GitHub Package Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/image:3.7.12-ohos-1.0.6

